whitelabel android tokenization

diff --git a/pgc-generate b/pgc-generate
--- a/pgc-generate
+++ b/pgc-generate
@@ -8,8 +8,28 @@ function __pgc_generate_main() {
 	local SCRIPT="$(__pgc_generate_realpath "$0")"
 	local DIR="$(dirname "$SCRIPT")"
 
+	local MODE="$1"
+	shift
+
+	case "${MODE}" in
+	"java-client")
+		local SELECTED_TEMPLATE="$DIR/pgc-java-client-template"
+		local GRADLE_TASKS="--gradle-task=xjc --gradle-task=javadoc --gradle-task=assemble"
+		local EXTRA_OPTIONS=""
+		;;
+	"tokenization-android")
+		local SELECTED_TEMPLATE="$DIR/pgc-tokenization-android-template"
+		local GRADLE_TASKS="--gradle-task=pgcclient-tokenization-api:javadoc --gradle-task=pgcclient-tokenization-api:assemble"
+		local EXTRA_OPTIONS="--disable-download-schemas"
+		;;
+	*)
+		>&2 echo "Invalid mode, use either \"java-client\" or \"tokenization-android\""
+		exit 1
+	esac
+
 	$DIR/gradlew shadowJar
-    java -jar $DIR/pgc-java-client-generator/build/libs/pgc-java-client-generator-1.0.jar --input-dir=$DIR/pgc-java-client-template $*
+    echo java -jar $DIR/pgc-java-client-generator/build/libs/pgc-java-client-generator-1.0.jar "--input-dir=$SELECTED_TEMPLATE" $EXTRA_OPTIONS $GRADLE_TASKS $*
+    java -jar $DIR/pgc-java-client-generator/build/libs/pgc-java-client-generator-1.0.jar "--input-dir=$SELECTED_TEMPLATE" $EXTRA_OPTIONS $GRADLE_TASKS $*
 }
 
 __pgc_generate_main $*
